---
kind: Template
apiVersion: v1
metadata:
  name: milvus-cpp-build-env
objects:
-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: milvus-cpp-build-env
    labels:
      app: milvus-cpp-build-env
  spec:
    replicas: 1
    selector:
      name: milvus-cpp-build-env
    template:
      metadata:
        labels:
          app: milvus-cpp-build-env
        name: milvus-cpp-build-env
      spec:
        containers:
        - image: "${MILVUS_BUILD_ENV_IMAGE}"
          command: ['tail', '-f', '/dev/null']
          name: milvus-cpp
          volumeMounts:
           - mountPath: /projects
             name: projects
          tty: true
          stdin: true
          env:
          - name: SHELL
            value: "/bin/bash"
        volumes:
         - name: projects
           persistentVolumeClaim:
             claimName: projects
-
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: projects
  spec:
    accessModes:
     - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
parameters:
- name: MILVUS_BUILD_ENV_IMAGE
  value: "milvusdb/milvus-dev:amd64-centos-7-core"
